steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/smelly-bot-repo/smelly-bot:$COMMIT_SHA
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/smelly-bot-repo/smelly-bot:$COMMIT_SHA

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - smelly-bot-run
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/smelly-bot-repo/smelly-bot:$COMMIT_SHA
      - --region=us-central1
      - --quiet

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
